// Downloads each song's MARKED snippet (Snippet Start → Snippet End, as set in
// Notion and mirrored in data/songs.js) as a self-hosted MP3 under
// public/audio/. These clips are the Instagram in-app-browser playback
// fallback — that WebView blocks cross-origin YouTube iframe playback, so we
// serve same-origin audio there instead. Every other browser still uses the
// YouTube iframe and never touches these files.
//
// Only the marked range is fetched (yt-dlp --download-sections), so we never
// download a full track — just the seconds between Snippet Start and Snippet
// End. Output filenames are keyed by song id (the Notion Slug) so they line up
// with SONG_CLIPS in data/songClips.js, which this script regenerates.
//
// Requirements: yt-dlp and ffmpeg on PATH.
//   Windows:  winget install yt-dlp.yt-dlp ; winget install Gyan.FFmpeg
//   (or: pip install -U yt-dlp, and grab ffmpeg from ffmpeg.org)
//
// Run:
//   node scripts/download-clips.mjs
//
import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync, existsSync, rmSync } from "node:fs";
import { FALLBACK_SONGS } from "../data/songs.js";

const OUT_DIR = "public/audio";
mkdirSync(OUT_DIR, { recursive: true });

const manifest = {};
const failures = [];

for (const song of FALLBACK_SONGS) {
  const { id, ytId } = song;
  if (!id || !ytId) continue;

  const startSec = (song.snippetStart ?? 0) / 1000;
  const endSec = song.snippetEnd != null ? song.snippetEnd / 1000 : null;
  const outPath = `${OUT_DIR}/${id}.mp3`;

  // Fetch ONLY the marked range. yt-dlp section syntax: "*START-END" in
  // seconds; "inf" as END means "to the end of the track". Downloading just
  // the section (not the whole video) is what honors the Notion snippet bounds
  // both on disk and at playback time — the served file already IS the clip.
  const section = `*${startSec}-${endSec != null ? endSec : "inf"}`;

  // Clean any stale output so a failed re-run can't leave a half file behind.
  try { if (existsSync(outPath)) rmSync(outPath); } catch {}

  const args = [
    "-x",
    "--audio-format", "mp3",
    "--audio-quality", "5",            // ~128 kbps VBR — good for web, small files
    "--download-sections", section,
    "--force-keyframes-at-cuts",       // accurate cut at the snippet bounds
    "--no-playlist",
    "-o", `${OUT_DIR}/${id}.%(ext)s`,
    `https://www.youtube.com/watch?v=${ytId}`,
  ];

  try {
    console.log(`↓ ${id}  (${startSec}s → ${endSec ?? "end"})`);
    execFileSync("yt-dlp", args, { stdio: "inherit" });
    if (existsSync(outPath)) {
      manifest[id] = `/audio/${id}.mp3`;
    } else {
      failures.push(id);
      console.error(`✗ ${id}: expected ${outPath} was not produced`);
    }
  } catch (err) {
    failures.push(id);
    console.error(`✗ ${id}: ${err.message}`);
  }
}

const body =
  "// AUTO-GENERATED by scripts/download-clips.mjs — do not edit by hand.\n" +
  "// Maps song id (Notion Slug) → self-hosted clipped-audio path in /public.\n" +
  "// Used ONLY as the Instagram in-app-browser playback fallback; every other\n" +
  "// browser plays via the YouTube iframe.\n" +
  `export const SONG_CLIPS = ${JSON.stringify(manifest, null, 2)};\n`;
writeFileSync("data/songClips.js", body);

console.log(
  `\n✓ ${Object.keys(manifest).length} clip(s) → ${OUT_DIR}, manifest → data/songClips.js`
);
if (failures.length) {
  console.log(`✗ ${failures.length} failed: ${failures.join(", ")}`);
  process.exitCode = 1;
}
